/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PaymentGatewayService } from "../paymentGateway.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Public } from "../../decorators/public.decorator";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PaymentGatewayCreateInput } from "./PaymentGatewayCreateInput";
import { PaymentGatewayWhereInput } from "./PaymentGatewayWhereInput";
import { PaymentGatewayWhereUniqueInput } from "./PaymentGatewayWhereUniqueInput";
import { PaymentGatewayFindManyArgs } from "./PaymentGatewayFindManyArgs";
import { PaymentGatewayUpdateInput } from "./PaymentGatewayUpdateInput";
import { PaymentGateway } from "./PaymentGateway";
import { PaymentRecordFindManyArgs } from "../../paymentRecord/base/PaymentRecordFindManyArgs";
import { PaymentRecord } from "../../paymentRecord/base/PaymentRecord";
import { PaymentRecordWhereUniqueInput } from "../../paymentRecord/base/PaymentRecordWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PaymentGatewayControllerBase {
  constructor(
    protected readonly service: PaymentGatewayService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "PaymentGateway",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PaymentGateway })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: PaymentGatewayCreateInput
  ): Promise<PaymentGateway> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @Public()
  @common.Get()
  @swagger.ApiOkResponse({ type: [PaymentGateway] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(PaymentGatewayFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<PaymentGateway[]> {
    const args = plainToClass(PaymentGatewayFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @Public()
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PaymentGateway })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: PaymentGatewayWhereUniqueInput
  ): Promise<PaymentGateway | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "PaymentGateway",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PaymentGateway })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: PaymentGatewayWhereUniqueInput,
    @common.Body() data: PaymentGatewayUpdateInput
  ): Promise<PaymentGateway | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "PaymentGateway",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PaymentGateway })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: PaymentGatewayWhereUniqueInput
  ): Promise<PaymentGateway | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "PaymentRecord",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/paymentRecords")
  @ApiNestedQuery(PaymentRecordFindManyArgs)
  async findManyPaymentRecords(
    @common.Req() request: Request,
    @common.Param() params: PaymentGatewayWhereUniqueInput
  ): Promise<PaymentRecord[]> {
    const query = plainToClass(PaymentRecordFindManyArgs, request.query);
    const results = await this.service.findPaymentRecords(params.id, {
      ...query,
      select: {
        amount: true,
        createdAt: true,
        frequency: true,
        id: true,

        paymentGateway: {
          select: {
            id: true,
          },
        },

        roomEnrollment: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "PaymentGateway",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/paymentRecords")
  async connectPaymentRecords(
    @common.Param() params: PaymentGatewayWhereUniqueInput,
    @common.Body() body: PaymentRecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      paymentRecords: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "PaymentGateway",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/paymentRecords")
  async updatePaymentRecords(
    @common.Param() params: PaymentGatewayWhereUniqueInput,
    @common.Body() body: PaymentRecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      paymentRecords: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "PaymentGateway",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/paymentRecords")
  async disconnectPaymentRecords(
    @common.Param() params: PaymentGatewayWhereUniqueInput,
    @common.Body() body: PaymentRecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      paymentRecords: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
