/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PlatformTierService } from "../platformTier.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Public } from "../../decorators/public.decorator";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PlatformTierCreateInput } from "./PlatformTierCreateInput";
import { PlatformTierWhereInput } from "./PlatformTierWhereInput";
import { PlatformTierWhereUniqueInput } from "./PlatformTierWhereUniqueInput";
import { PlatformTierFindManyArgs } from "./PlatformTierFindManyArgs";
import { PlatformTierUpdateInput } from "./PlatformTierUpdateInput";
import { PlatformTier } from "./PlatformTier";
import { RoomFindManyArgs } from "../../room/base/RoomFindManyArgs";
import { Room } from "../../room/base/Room";
import { RoomWhereUniqueInput } from "../../room/base/RoomWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PlatformTierControllerBase {
  constructor(
    protected readonly service: PlatformTierService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "PlatformTier",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PlatformTier })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: PlatformTierCreateInput
  ): Promise<PlatformTier> {
    return await this.service.create({
      data: {
        ...data,

        provider: {
          connect: data.provider,
        },
      },
      select: {
        capcity: true,
        createdAt: true,
        id: true,
        name: true,
        price: true,

        provider: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @Public()
  @common.Get()
  @swagger.ApiOkResponse({ type: [PlatformTier] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(PlatformTierFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<PlatformTier[]> {
    const args = plainToClass(PlatformTierFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        capcity: true,
        createdAt: true,
        id: true,
        name: true,
        price: true,

        provider: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @Public()
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PlatformTier })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: PlatformTierWhereUniqueInput
  ): Promise<PlatformTier | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        capcity: true,
        createdAt: true,
        id: true,
        name: true,
        price: true,

        provider: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "PlatformTier",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PlatformTier })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: PlatformTierWhereUniqueInput,
    @common.Body() data: PlatformTierUpdateInput
  ): Promise<PlatformTier | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          provider: {
            connect: data.provider,
          },
        },
        select: {
          capcity: true,
          createdAt: true,
          id: true,
          name: true,
          price: true,

          provider: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "PlatformTier",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PlatformTier })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: PlatformTierWhereUniqueInput
  ): Promise<PlatformTier | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          capcity: true,
          createdAt: true,
          id: true,
          name: true,
          price: true,

          provider: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Room",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/rooms")
  @ApiNestedQuery(RoomFindManyArgs)
  async findManyRooms(
    @common.Req() request: Request,
    @common.Param() params: PlatformTierWhereUniqueInput
  ): Promise<Room[]> {
    const query = plainToClass(RoomFindManyArgs, request.query);
    const results = await this.service.findRooms(params.id, {
      ...query,
      select: {
        allowedFrequency: true,
        billingDate: true,
        capcity: true,
        createdAt: true,
        id: true,

        owner: {
          select: {
            id: true,
          },
        },

        platformTier: {
          select: {
            id: true,
          },
        },

        remainingCapcity: true,
        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "PlatformTier",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/rooms")
  async connectRooms(
    @common.Param() params: PlatformTierWhereUniqueInput,
    @common.Body() body: RoomWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      rooms: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "PlatformTier",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/rooms")
  async updateRooms(
    @common.Param() params: PlatformTierWhereUniqueInput,
    @common.Body() body: RoomWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      rooms: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "PlatformTier",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/rooms")
  async disconnectRooms(
    @common.Param() params: PlatformTierWhereUniqueInput,
    @common.Body() body: RoomWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      rooms: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
