/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { RoomEnrollmentService } from "../roomEnrollment.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RoomEnrollmentCreateInput } from "./RoomEnrollmentCreateInput";
import { RoomEnrollmentWhereInput } from "./RoomEnrollmentWhereInput";
import { RoomEnrollmentWhereUniqueInput } from "./RoomEnrollmentWhereUniqueInput";
import { RoomEnrollmentFindManyArgs } from "./RoomEnrollmentFindManyArgs";
import { RoomEnrollmentUpdateInput } from "./RoomEnrollmentUpdateInput";
import { RoomEnrollment } from "./RoomEnrollment";
import { PaymentRecordFindManyArgs } from "../../paymentRecord/base/PaymentRecordFindManyArgs";
import { PaymentRecord } from "../../paymentRecord/base/PaymentRecord";
import { PaymentRecordWhereUniqueInput } from "../../paymentRecord/base/PaymentRecordWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RoomEnrollmentControllerBase {
  constructor(
    protected readonly service: RoomEnrollmentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "RoomEnrollment",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: RoomEnrollment })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: RoomEnrollmentCreateInput
  ): Promise<RoomEnrollment> {
    return await this.service.create({
      data: {
        ...data,

        room: {
          connect: data.room,
        },

        user: {
          connect: data.user,
        },
      },
      select: {
        createdAt: true,
        id: true,

        room: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "RoomEnrollment",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [RoomEnrollment] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(RoomEnrollmentFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<RoomEnrollment[]> {
    const args = plainToClass(RoomEnrollmentFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,

        room: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "RoomEnrollment",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: RoomEnrollment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: RoomEnrollmentWhereUniqueInput
  ): Promise<RoomEnrollment | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,

        room: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "RoomEnrollment",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: RoomEnrollment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: RoomEnrollmentWhereUniqueInput,
    @common.Body() data: RoomEnrollmentUpdateInput
  ): Promise<RoomEnrollment | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          room: {
            connect: data.room,
          },

          user: {
            connect: data.user,
          },
        },
        select: {
          createdAt: true,
          id: true,

          room: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "RoomEnrollment",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: RoomEnrollment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: RoomEnrollmentWhereUniqueInput
  ): Promise<RoomEnrollment | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,

          room: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "PaymentRecord",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/paymentRecords")
  @ApiNestedQuery(PaymentRecordFindManyArgs)
  async findManyPaymentRecords(
    @common.Req() request: Request,
    @common.Param() params: RoomEnrollmentWhereUniqueInput
  ): Promise<PaymentRecord[]> {
    const query = plainToClass(PaymentRecordFindManyArgs, request.query);
    const results = await this.service.findPaymentRecords(params.id, {
      ...query,
      select: {
        amount: true,
        createdAt: true,
        frequency: true,
        id: true,

        paymentGateway: {
          select: {
            id: true,
          },
        },

        roomEnrollment: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "RoomEnrollment",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/paymentRecords")
  async connectPaymentRecords(
    @common.Param() params: RoomEnrollmentWhereUniqueInput,
    @common.Body() body: PaymentRecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      paymentRecords: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "RoomEnrollment",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/paymentRecords")
  async updatePaymentRecords(
    @common.Param() params: RoomEnrollmentWhereUniqueInput,
    @common.Body() body: PaymentRecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      paymentRecords: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "RoomEnrollment",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/paymentRecords")
  async disconnectPaymentRecords(
    @common.Param() params: RoomEnrollmentWhereUniqueInput,
    @common.Body() body: PaymentRecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      paymentRecords: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
