/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { TagUpdateManyWithoutPlatformProvidersInput } from "./TagUpdateManyWithoutPlatformProvidersInput";
import { Type } from "class-transformer";
import { PlatformTierUpdateManyWithoutPlatformProvidersInput } from "./PlatformTierUpdateManyWithoutPlatformProvidersInput";
@InputType()
class PlatformProviderUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  bannerImage?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  iconImage?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: () => TagUpdateManyWithoutPlatformProvidersInput,
  })
  @ValidateNested()
  @Type(() => TagUpdateManyWithoutPlatformProvidersInput)
  @IsOptional()
  @Field(() => TagUpdateManyWithoutPlatformProvidersInput, {
    nullable: true,
  })
  tags?: TagUpdateManyWithoutPlatformProvidersInput;

  @ApiProperty({
    required: false,
    type: () => PlatformTierUpdateManyWithoutPlatformProvidersInput,
  })
  @ValidateNested()
  @Type(() => PlatformTierUpdateManyWithoutPlatformProvidersInput)
  @IsOptional()
  @Field(() => PlatformTierUpdateManyWithoutPlatformProvidersInput, {
    nullable: true,
  })
  tiers?: PlatformTierUpdateManyWithoutPlatformProvidersInput;
}
export { PlatformProviderUpdateInput };
