/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { RoomService } from "../room.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RoomCreateInput } from "./RoomCreateInput";
import { RoomWhereInput } from "./RoomWhereInput";
import { RoomWhereUniqueInput } from "./RoomWhereUniqueInput";
import { RoomFindManyArgs } from "./RoomFindManyArgs";
import { RoomUpdateInput } from "./RoomUpdateInput";
import { Room } from "./Room";
import { RoomEnrollmentFindManyArgs } from "../../roomEnrollment/base/RoomEnrollmentFindManyArgs";
import { RoomEnrollment } from "../../roomEnrollment/base/RoomEnrollment";
import { RoomEnrollmentWhereUniqueInput } from "../../roomEnrollment/base/RoomEnrollmentWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RoomControllerBase {
  constructor(
    protected readonly service: RoomService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Room",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Room })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: RoomCreateInput): Promise<Room> {
    return await this.service.create({
      data: {
        ...data,

        owner: {
          connect: data.owner,
        },

        platformTier: {
          connect: data.platformTier,
        },
      },
      select: {
        allowedFrequency: true,
        billingDate: true,
        capcity: true,
        createdAt: true,
        id: true,

        owner: {
          select: {
            id: true,
          },
        },

        platformTier: {
          select: {
            id: true,
          },
        },

        remainingCapcity: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Room",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Room] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(RoomFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Room[]> {
    const args = plainToClass(RoomFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        allowedFrequency: true,
        billingDate: true,
        capcity: true,
        createdAt: true,
        id: true,

        owner: {
          select: {
            id: true,
          },
        },

        platformTier: {
          select: {
            id: true,
          },
        },

        remainingCapcity: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Room",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Room })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: RoomWhereUniqueInput
  ): Promise<Room | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        allowedFrequency: true,
        billingDate: true,
        capcity: true,
        createdAt: true,
        id: true,

        owner: {
          select: {
            id: true,
          },
        },

        platformTier: {
          select: {
            id: true,
          },
        },

        remainingCapcity: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Room",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Room })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: RoomWhereUniqueInput,
    @common.Body() data: RoomUpdateInput
  ): Promise<Room | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          owner: {
            connect: data.owner,
          },

          platformTier: {
            connect: data.platformTier,
          },
        },
        select: {
          allowedFrequency: true,
          billingDate: true,
          capcity: true,
          createdAt: true,
          id: true,

          owner: {
            select: {
              id: true,
            },
          },

          platformTier: {
            select: {
              id: true,
            },
          },

          remainingCapcity: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Room",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Room })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: RoomWhereUniqueInput
  ): Promise<Room | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          allowedFrequency: true,
          billingDate: true,
          capcity: true,
          createdAt: true,
          id: true,

          owner: {
            select: {
              id: true,
            },
          },

          platformTier: {
            select: {
              id: true,
            },
          },

          remainingCapcity: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "RoomEnrollment",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/enrollments")
  @ApiNestedQuery(RoomEnrollmentFindManyArgs)
  async findManyEnrollments(
    @common.Req() request: Request,
    @common.Param() params: RoomWhereUniqueInput
  ): Promise<RoomEnrollment[]> {
    const query = plainToClass(RoomEnrollmentFindManyArgs, request.query);
    const results = await this.service.findEnrollments(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        room: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Room",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/enrollments")
  async connectEnrollments(
    @common.Param() params: RoomWhereUniqueInput,
    @common.Body() body: RoomEnrollmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      enrollments: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Room",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/enrollments")
  async updateEnrollments(
    @common.Param() params: RoomWhereUniqueInput,
    @common.Body() body: RoomEnrollmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      enrollments: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Room",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/enrollments")
  async disconnectEnrollments(
    @common.Param() params: RoomWhereUniqueInput,
    @common.Body() body: RoomEnrollmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      enrollments: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
