/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumRoomAllowedFrequency } from "./EnumRoomAllowedFrequency";
import {
  IsEnum,
  IsOptional,
  IsDate,
  IsInt,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { RoomEnrollmentCreateNestedManyWithoutRoomsInput } from "./RoomEnrollmentCreateNestedManyWithoutRoomsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { PlatformTierWhereUniqueInput } from "../../platformTier/base/PlatformTierWhereUniqueInput";
import { EnumRoomStatus } from "./EnumRoomStatus";
@InputType()
class RoomCreateInput {
  @ApiProperty({
    required: true,
    enum: EnumRoomAllowedFrequency,
    isArray: true,
  })
  @IsEnum(EnumRoomAllowedFrequency, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumRoomAllowedFrequency], {
    nullable: true,
  })
  allowedFrequency?: Array<"OneOff" | "Failed" | "Pending">;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  billingDate!: Date;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => Number)
  capcity!: number;

  @ApiProperty({
    required: true,
    type: () => RoomEnrollmentCreateNestedManyWithoutRoomsInput,
  })
  @ValidateNested()
  @Type(() => RoomEnrollmentCreateNestedManyWithoutRoomsInput)
  @IsOptional()
  @Field(() => RoomEnrollmentCreateNestedManyWithoutRoomsInput, {
    nullable: true,
  })
  enrollments?: RoomEnrollmentCreateNestedManyWithoutRoomsInput;

  @ApiProperty({
    required: true,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @Field(() => UserWhereUniqueInput)
  owner!: UserWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => PlatformTierWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PlatformTierWhereUniqueInput)
  @Field(() => PlatformTierWhereUniqueInput)
  platformTier!: PlatformTierWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => Number)
  remainingCapcity!: number;

  @ApiProperty({
    required: true,
    enum: EnumRoomStatus,
  })
  @IsEnum(EnumRoomStatus)
  @Field(() => EnumRoomStatus)
  status!: "Public" | "Private" | "Archive";
}
export { RoomCreateInput };
